### ISSUE TITLE
Event List v1 Checklist

### ISSUE THREAD

**Issue by vinibgoulart** [event-list/event-list#2]
- [ ] Admin checklist https://github.com/event-list/event-list/issues/3
- [ ] Web checklist https://github.com/event-list/event-list/issues/4
- [ ] Server checklist https://github.com/event-list/event-list/issues/5
