### ISSUE TITLE
Web v1 Checklist

### ISSUE THREAD

**Issue by vinibgoulart** [event-list/event-list#4]
- [ ] event place - https://github.com/event-list/event-list/issues/6
- [ ] users on event
- [ ] fix input mask in share event form - #7 

Done
- [x] write jest tests
